name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Helm
        uses: azure/setup-helm@v2

      - name: Setup chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Correctly set the CR_TOKEN environment variable

      - name: Run chart-releaser
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          helm repo index ./charts --url https://lanceapps.github.io/tasks/
          cr upload -o lanceapps -r tasks -t ${{ secrets.GITHUB_TOKEN }}
